### ISSUE TITLE
Not redirect to secured page after login succeed

### ISSUE THREAD

**Issue by hendisantika** [asholokh/google-auth-sample#1]
Nice article.
I try to clone your repo and run it. But It seem Not redirect to secured page after login succeed.

Any advice?
Thanks

**Comment by liyakamilia** [comment]
Hi sholokh, I got the same issue with @hendisantika, thank you

**Comment by asholokh** [comment]
Hello!
Thank you for feedback, @hendisantika and @liyakamilia !
I have found one issue in the code which was causing the login issue. Look at today's commit for more details.
Another possible reason, why authentication may fail is different time on the server, where this application is deployed, and the phone where Google Authentication is installed and used. So make sure that on both devices time is synchronized and correct.
